### ISSUE TITLE
Pass command-line options to docker-selenium

### ISSUE THREAD

**Issue by diemol** [zalando-incubator/zalenium#11]
Zalenium is starting the docker-containers with a fixed set of command-line parameters, which limits the usability for others that already use docker-selenium with a broader set of command-line parameters (e.g. timezone, noVNC, resolution, etc.)

Zalenium should be able to grab somehow extra parameters to allow a more custom fitted docker-selenium configuration. One alternative is via an environment variable.

Suggested by [criscodex](https://github.com/criscodex)

**Comment by diemol** [comment]
[criscodex](https://github.com/criscodex), 

could you please give us some examples of command line parameters that you are using?

**Comment by elgalu** [comment]
Good question, I'm also intrigued about what @criscodex is using:)

Probably necessary (I'll include the defaults):

    SCREEN_WIDTH="1900"
    SCREEN_HEIGHT="1880"
    SELENIUM_HUB_PARAMS=""
    SELENIUM_NODE_PARAMS=""
    CHROME_ARGS="--no-sandbox --disable-gpu"

Unclear to me if necessary

    VIDEO_FILE_NAME=""
    SEL_RELEASE_TIMEOUT_SECS="19000"
    SEL_BROWSER_TIMEOUT_SECS="16000"
    SELENIUM_NODE_REGISTER_CYCLE="1000"
    SELENIUM_NODE_PROXY_PARAMS=""
    SEL_CLEANUPCYCLE_MS="2000"
    SEL_NODEPOLLING_MS="1500"
    SEL_UNREGISTER_IF_STILL_DOWN_AFTER="2500"
    SCREEN_MAIN_DEPTH="24"
    SCREEN_SUB_DEPTH="32"
    NOVNC="false"
    NOVNC_PORT="6080"
    FFMPEG_CODEC_ARGS="-vcodec libx264 -crf 0 -preset ultrafast"

For VNC they might pass "true" but is unclear how they will know to which container host to connect

    VNC_START="true"
    VNC_PORT="25900"

**Comment by criscodex** [comment]
I'm using the following command-line parameters:

> docker run -d --name=grid -p 4444:24444 -p 5999:25900 --shm-size=1g -e VNC_PASSWORD=no -e TZ="America/Montreal" -e SCREEN_WIDTH=1440 -e SCREEN_HEIGHT=810 -e RC_CHROME=false -e RC_FIREFOX=false -p 6080:26080 -e NOVNC=true elgalu/selenium:2.53.1z

**Comment by diemol** [comment]
Hi @criscodex,

We did another [release](https://github.com/zalando-incubator/zalenium/releases/tag/2.53.1c) which for now allows to add the common options screen width, height and time zone.

If you are still eager to, maybe you can give it a try :)

I guess the command that works for you is:

```sh
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    dosel/zalenium start --sauceLabsEnabled false --screenWidth 1440 --screenHeight 810 --timeZone "America/Montreal"
```

For the VNC part, we will tackle it in a different way, I think we will implement a servlet to see all the running tests.

**Comment by diemol** [comment]
I will close this issue for now since it was solved in a previous release, please comment or reopen if something is not working as expected.
