### ISSUE TITLE
Enable/disable VNC

### ISSUE THREAD

**Issue by diemol** [zalando-incubator/zalenium#21]
docker-selenium provides the possibility to see the test activity through VNC. We need to figure out a default behaviour of this feature though Zalenium.

**Comment by rhehl** [comment]
That's really a great feature! But i've a small problem: it look's like localhost is hardcoded for VNC and my Zalenium doesn't run at my localhost would it be possible to add a parameter to define this hostname?

**Comment by diemol** [comment]
Hi @rhehl,

Thanks for trying Zalenium!

Somehow we didn't think about that, we just hardcoded `localhost` and that's it. But you say makes a lot of sense, running Zalenium in one machine and just checking the running tests from another one, it is just that we didn't think about that scenario.

Anyway, in the release done a few moments ago [2.53.1h](https://github.com/zalando-incubator/zalenium/releases/tag/2.53.1h), this feature was included. We tried it here and it seems to be working fine, but please go ahead and pull the latest container and please try it...

If you have any more feedback, doubts or questions, don't hesitate to create an issue.

**Comment by diemol** [comment]
I'll close this issue since no more feedback was given, if there is any related issue, please comment or reopen.
