### ISSUE TITLE
/var/log/cont/video-rec-stdout.log: No such file or directory

### ISSUE THREAD

**Issue by ryudice** [zalando-incubator/zalenium#34]
Hello,
I keep getting this error when starting a test:

.grep: /var/log/cont/video-rec-stdout.log: No such file or directory
.ERROR: Failed while waiting for video recording to start!

I already checked that the videos volume is mounted and it is. Also ran the container with --privileged.

Any ideas?

**Comment by diemol** [comment]
Hi @ryudice,

Can you please paste here the docker command you use to start Zalenium? Also the version of Zalenium and docker-selenium that you are using?

**Comment by ryudice** [comment]
Docker command is 

docker run --rm -ti --name zalenium -p 4444:4444 -p 5555:5555   -v $(which docker):/usr/bin/docker   -v /var/run/docker.sock:/var/run/docker.sock   -v /tmp/videos:/home/seluser/videos --privileged  dosel/zalenium start --sauceLabsEnabled false

These are the versions:

![image](https://cloud.githubusercontent.com/assets/125211/21027074/e072ddc0-bd54-11e6-98c8-3b45d0827a55.png)

**Comment by diemol** [comment]
Hi,

We have released a new version with more logging, maybe this helps us to identify the issue better. We tried it here but we could not reproduce it. Our log looks like [this](https://gist.github.com/elgalu/634953497956e99039828a8170b55a12)

Could you please try to use the new version, perhaps compare the logs, and if it still fails, can you give please paste in a gist or here the complete output of Zalenium?

Thanks!

**Comment by ryudice** [comment]
I think it was an issue with the host, I was using RancherOS as host, I switched to an Ubuntu host and seems fine so far, I'll let you know how it goes.

**Comment by ryudice** [comment]
All good so far, thanks for your help.
