### ISSUE TITLE
Choosing the video recording file names

### ISSUE THREAD

**Issue by ryudice** [zalando-incubator/zalenium#35]
Is there anyway to change the way the recording file names are generated? I'm looking to use the test case name.

**Comment by diemol** [comment]
To use the test name case for the video file name makes a lot of sense, it just makes it easier to know the contents of the file just by checking the name.

I think we can implement it soon because in theory it should not be that complicated.

I'll post something here when we are done with it :)

**Comment by diemol** [comment]
Implemented in https://github.com/zalando-incubator/zalenium/pull/36, should be released between today and tomorrow, or whenever Travis wants to process the build...

**Comment by diemol** [comment]
Hi @ryudice,

We just released this some hours ago. If you want to, go ahead and pull the latest version and try it.

The files should be saved now like "testName_browser_containerPort_timeStamp.mkv".

**Comment by ryudice** [comment]
Thanks a lot, I will pull the image right away and let you know how it works. :)

**Comment by ryudice** [comment]
Hi @diemol,
for some reason the filename that I get is this "vid_firefox_40002_20161213220536.mkv", I suppose "vid" should be the test name, is there something I need to do?

**Comment by diemol** [comment]
In the desired capabilities of your test, you should add a new one called "name". In java it would look like:

```java
desiredCapabilities.setCapability(CapabilityType.BROWSER_NAME, BrowserType.FIREFOX);
desiredCapabilities.setCapability(CapabilityType.PLATFORM, Platform.LINUX);
desiredCapabilities.setCapability("name", "testName");
```

**Comment by ryudice** [comment]
Thanks @diemol, it's working good :)
